Repository Talend/daikon, pull requests merged in 2018-10, with the labels that each got.

#405 fix(TESB-23714): Add bundle package for signature verifier
  daikon-signature-verifier/pom.xml
Labels: Merged build passed

#406 fix(TESB-23714): Add bundle package for signature verifier (2)
  daikon-signature-verifier/pom.xml
Labels: Merged build passed

#407 chore(TDQ-15975): Adapt japanese char-pattern with half-width / fullw…
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Comply.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPattern.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegex.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegexConstants.java
  daikon/src/test/java/org/talend/daikon/pattern/character/CharPatternToRegexTest.java
Labels: Can be merged, Merged build passed

#399 fix(TDKN-202): Add a dot to the end of message in daikon-audit
  daikon-audit/audit-common/src/main/java/org/talend/logging/audit/StandardEventAuditLogger.java
  daikon-audit/audit-common/src/test/java/org/talend/logging/audit/EventAuditLoggerTest.java
Labels: Merged build passed

#408 feat(TDQ-15966): adapt word pattern for japanese
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_WordComply.java
  daikon/src/main/java/org/talend/daikon/pattern/PatternRegexUtils.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegex.java
  daikon/src/main/java/org/talend/daikon/pattern/word/WordPattern.java
  daikon/src/main/java/org/talend/daikon/pattern/word/WordPatternToRegexConstants.java
  daikon/src/test/java/org/talend/daikon/pattern/word/WordPatternToRegexTest.java
Labels: Merged build passed

#410 fix(TDQ-15964): handle special japanese characters in char-patterns
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Comply.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_WordComply.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPattern.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegexConstants.java
  daikon/src/test/java/org/talend/daikon/pattern/character/CharPatternToRegexTest.java
Labels: Merged build passed, Need review

#411 fix(cumulative): Cumulative fixes for daikon
  daikon-service/pom.xml
  daikon-spring/daikon-spring-mongo/pom.xml
  pom.xml
Labels: Merged build passed

#413 chore(release): Release 0.27.0
  daikon-audit/audit-all/pom.xml
  daikon-audit/audit-common/pom.xml
  daikon-audit/audit-log4j1/pom.xml
  daikon-audit/audit-logback/pom.xml
  daikon-audit/pom.xml
  daikon-content-service/content-service-common/pom.xml
  daikon-content-service/content-service-journal-mongo/pom.xml
  daikon-content-service/content-service-journal/pom.xml
  daikon-content-service/local-content-service/pom.xml
  daikon-content-service/pom.xml
  daikon-content-service/s3-content-service/pom.xml
  daikon-i18n/pom.xml
  daikon-logging/logging-event-layout/pom.xml
  daikon-logging/logging-http-headers/pom.xml
  daikon-logging/logging-kafka-interceptor/pom.xml
  daikon-logging/logging-request-interceptor/pom.xml
  daikon-logging/logging-spring-security/pom.xml
  daikon-logging/pom.xml
  daikon-messages/messages-demo/demo-listener/pom.xml
  daikon-messages/messages-demo/demo-producer/pom.xml
  daikon-messages/messages-demo/pom.xml
  daikon-messages/messages-model-spring-support/pom.xml
  daikon-messages/messages-model/pom.xml
  daikon-messages/pom.xml
  daikon-multitenant/multitenant-core/pom.xml
  daikon-multitenant/multitenant-spring-async/pom.xml
  daikon-multitenant/multitenant-spring-web/pom.xml
  daikon-multitenant/pom.xml
  daikon-service/pom.xml
  daikon-service/service-common/pom.xml
  daikon-service/service-docs/pom.xml
  daikon-service/service-examples/dashboard-service/pom.xml
  daikon-service/service-examples/pom.xml
  daikon-service/service-examples/weather-service/pom.xml
  daikon-service/service-parent/pom.xml
  daikon-signature-verifier/pom.xml
  daikon-spring/daikon-spring-mongo/pom.xml
  daikon-spring/daikon-spring-security/pom.xml
  daikon-spring/daikon-spring-tenancy/pom.xml
  daikon-spring/daikon-spring-utils/pom.xml
  daikon-spring/daikon-spring-zipkin/pom.xml
  daikon-spring/pom.xml
  daikon-tql/daikon-tql-bean/pom.xml
  daikon-tql/daikon-tql-core/pom.xml
  daikon-tql/daikon-tql-mongo/pom.xml
  daikon-tql/pom.xml
  daikon/pom.xml
  pom.xml
  reporting/pom.xml
Labels: Merged build passed

#414 chore: separate plugin from plugin management
  daikon-content-service/pom.xml
  daikon-service/service-parent/pom.xml
  pom.xml
Labels: Merged build passed, Need review

#415 fix(TDQ-16037): remove redundant curly braces in KANJI_RARE regex
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegexConstants.java
  daikon/src/test/java/org/talend/daikon/pattern/character/CharPatternToRegexTest.java
Labels: Merged build passed
