Repository Talend/daikon, pull requests merged in 2018-03, with the labels that each got.

#343 fix(TDKN-190): serialize the version number when serializing properti…
  daikon/src/main/java/org/talend/daikon/properties/PropertiesImpl.java
  daikon/src/main/java/org/talend/daikon/serialize/SerializerDeserializer.java
  daikon/src/test/java/org/talend/daikon/serialize/jsonio/PersistenceTestObject.java
Labels: Merged build passed, Need review

#344 fix(TDKN-190): serialize the version number when serializing properti…
  daikon/src/main/java/org/talend/daikon/properties/PropertiesImpl.java
  daikon/src/main/java/org/talend/daikon/serialize/SerializerDeserializer.java
  daikon/src/test/java/org/talend/daikon/serialize/jsonio/PersistenceTestObject.java
Labels: Merged build passed

#345 fix(TDP-5356): Reuse of mongo clients may lead to closed clients.
  daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/CachedMongoClientProvider.java
  daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/MongoClientProvider.java
  daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/SimpleMongoClientProvider.java
  daikon-spring/daikon-spring-mongo/src/main/java/org/talend/daikon/spring/mongo/SynchronizedMongoClientProvider.java
  daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/AbstractMultiTenantMongoDbTest.java
  daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/CachedMongoClientProviderTest.java
  daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/SynchronizedMongoClientProviderTest.java
  daikon-spring/daikon-spring-mongo/src/test/java/org/talend/daikon/spring/mongo/TestMultiTenantConfiguration.java
Labels: Merged build passed, Need review

#342 fix(TFD-2647): Update numeric and string functions to support formats.
  daikon/src/main/java/org/talend/daikon/converter/BooleanConverter.java
  daikon/src/main/java/org/talend/daikon/converter/ByteConverter.java
  daikon/src/main/java/org/talend/daikon/converter/DoubleConverter.java
  daikon/src/main/java/org/talend/daikon/converter/FloatConverter.java
  daikon/src/main/java/org/talend/daikon/converter/IntegerConverter.java
  daikon/src/main/java/org/talend/daikon/converter/LocalDateConverter.java
  daikon/src/main/java/org/talend/daikon/converter/LocalDateTimeConverter.java
  daikon/src/main/java/org/talend/daikon/converter/LocalTimeConverter.java
  daikon/src/main/java/org/talend/daikon/converter/LongConverter.java
  daikon/src/main/java/org/talend/daikon/converter/NumberConverter.java
  daikon/src/main/java/org/talend/daikon/converter/ShortConverter.java
  daikon/src/main/java/org/talend/daikon/converter/StringConverter.java
  daikon/src/main/java/org/talend/daikon/converter/TypeConverter.java
  daikon/src/main/java/org/talend/daikon/converter/TypeConverterErrorCode.java
  daikon/src/main/java/org/talend/daikon/converter/WithFormatConverter.java
  daikon/src/test/java/org/talend/daikon/avro/SampleSchemas.java
  daikon/src/test/java/org/talend/daikon/converter/LocalDateConverterTest.java
  daikon/src/test/java/org/talend/daikon/converter/LocalDateTimeConverterTest.java
  daikon/src/test/java/org/talend/daikon/converter/LocalTimeConverterTest.java
  daikon/src/test/java/org/talend/daikon/converter/TypeConverterTest.java
Labels: Merged build passed

#349 chore(): normalized kafka messages with avro
  daikon-messages/messages-demo/demo-service1/src/main/resources/application.properties
  daikon-messages/messages-demo/demo-service2/src/main/resources/application.properties
  daikon-messages/messages-model-spring-support/pom.xml
  daikon-messages/messages-model-spring-support/src/main/java/org/talend/daikon/messages/spring/consumer/EnableMessagesConsumerAutoConfig.java
  daikon-messages/messages-model-spring-support/src/main/java/org/talend/daikon/messages/spring/consumer/MultiTenantConsumerSettersConfiguration.java
  daikon-messages/messages-model-spring-support/src/main/java/org/talend/daikon/messages/spring/producer/DefaultProducerProvidersConfiguration.java
  daikon-messages/messages-model-spring-support/src/main/java/org/talend/daikon/messages/spring/producer/EnableMessagesProducerAutoConfig.java
  daikon-messages/messages-model-spring-support/src/main/java/org/talend/daikon/messages/spring/producer/MultiTenantProducerProvidersConfiguration.java
  daikon-messages/messages-model/pom.xml
  daikon-messages/messages-model/src/main/avro/MessageHeader.avsc
  daikon-messages/messages-model/src/main/java/org/talend/daikon/messages/header/producer/MessageHeaderFactory.java
  daikon-messages/messages-model/src/main/java/org/talend/daikon/messages/header/producer/MessageHeaderFactoryImpl.java
  daikon-messages/messages-model/src/main/java/org/talend/daikon/messages/header/producer/ServiceInfoProvider.java
  daikon-messages/messages-model/src/main/java/org/talend/daikon/messages/serialization/DaikonMessageKeyDeserializer.java
  daikon-messages/messages-model/src/main/java/org/talend/daikon/messages/serialization/DaikonMessageKeySerializer.java
  daikon-messages/messages-model/src/test/java/org/talend/daikon/messages/header/TestMessageHeaderExtractor.java
  daikon-messages/messages-model/src/test/java/org/talend/daikon/messages/header/TestMessageHeaderFactoryImpl.java
Labels: Merged build passed

#351 fix(TFD-3558): Add ui:placeholder value in JSON Schema.
  daikon/src/main/java/org/talend/daikon/properties/presentation/Widget.java
  daikon/src/main/java/org/talend/daikon/serialize/jsonschema/JsonDataGenerator.java
  daikon/src/main/java/org/talend/daikon/serialize/jsonschema/JsonSchemaUtil.java
  daikon/src/main/java/org/talend/daikon/serialize/jsonschema/UiSchemaConstants.java
  daikon/src/main/java/org/talend/daikon/serialize/jsonschema/UiSchemaGenerator.java
  daikon/src/test/java/org/talend/daikon/serialize/FullExampleProperties.java
  daikon/src/test/java/org/talend/daikon/serialize/jsonschema/JsonDataGeneratorTest.java
  daikon/src/test/java/org/talend/daikon/serialize/jsonschema/JsonSchemaUtilTest.java
  daikon/src/test/resources/org/talend/daikon/serialize/FullExampleProperties.properties
  daikon/src/test/resources/org/talend/daikon/serialize/jsonschema/FullExampleJsonSchema.json
  daikon/src/test/resources/org/talend/daikon/serialize/jsonschema/FullExampleUiSchema.json
Labels: Merged build passed

#352 fix(TFD-2616): uniqueItems value should be boolean
  daikon/src/main/java/org/talend/daikon/serialize/jsonschema/WidgetSpecificJsonSchemaUtils.java
  daikon/src/test/java/org/talend/daikon/serialize/jsonschema/JsonSchemaGeneratorTest.java
Labels: Merged build passed

#346 chore(TDI-39894): upgrade jackson version
  daikon-audit/pom.xml
  daikon-content-service/content-service-common/pom.xml
  daikon-content-service/local-content-service/pom.xml
  daikon-content-service/pom.xml
  daikon-content-service/s3-content-service/pom.xml
  daikon-i18n/pom.xml
  daikon-logging/logging-event-layout/pom.xml
  daikon-logging/logging-http-headers/pom.xml
  daikon-logging/logging-kafka-interceptor/pom.xml
  daikon-logging/logging-request-interceptor/pom.xml
  daikon-logging/logging-spring-security/pom.xml
  daikon-logging/pom.xml
  daikon-multitenant/multitenant-core/pom.xml
  daikon-multitenant/multitenant-spring-async/pom.xml
  daikon-multitenant/multitenant-spring-web/pom.xml
  daikon-multitenant/pom.xml
  daikon-service/pom.xml
  daikon-service/service-common/pom.xml
  daikon-service/service-docs/pom.xml
  daikon-service/service-examples/dashboard-service/pom.xml
  daikon-service/service-examples/pom.xml
  daikon-service/service-examples/weather-service/pom.xml
  daikon-service/service-parent/pom.xml
  daikon-spring/daikon-spring-mongo/pom.xml
  daikon-spring/daikon-spring-security/pom.xml
  daikon-spring/daikon-spring-tenancy/pom.xml
  daikon-spring/daikon-spring-utils/pom.xml
  daikon-spring/pom.xml
  daikon-tql/daikon-tql-bean/pom.xml
  daikon-tql/daikon-tql-core/pom.xml
  daikon-tql/daikon-tql-mongo/pom.xml
  daikon-tql/pom.xml
  daikon/pom.xml
  daikon/src/test/java/org/talend/daikon/converter/TypeConverterTest.java
  pom.xml
  reporting/pom.xml
Labels: Can be merged, Merged build passed

#354 feat(TDS-3154): support single quotes in TQL queries
  daikon-tql/daikon-tql-core/src/main/antlr4/TqlLexer.g4
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/parser/TqlExpressionVisitor.java
  daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/api/TestTqlApi_Comply.java
  daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/api/TestTqlApi_Contains.java
  daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/api/TestTqlApi_FieldComparison.java
  daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/api/TestTqlApi_Match.java
Labels: Merged build passed, Need review

#356 Bump snapshot version
  daikon-audit/pom.xml
  daikon-content-service/content-service-common/pom.xml
  daikon-content-service/local-content-service/pom.xml
  daikon-content-service/pom.xml
  daikon-content-service/s3-content-service/pom.xml
  daikon-i18n/pom.xml
  daikon-logging/logging-event-layout/pom.xml
  daikon-logging/logging-http-headers/pom.xml
  daikon-logging/logging-kafka-interceptor/pom.xml
  daikon-logging/logging-request-interceptor/pom.xml
  daikon-logging/logging-spring-security/pom.xml
  daikon-logging/pom.xml
  daikon-messages/messages-demo/demo-listener/pom.xml
  daikon-messages/messages-demo/demo-producer/pom.xml
  daikon-messages/messages-demo/pom.xml
  daikon-messages/messages-model-spring-support/pom.xml
  daikon-messages/messages-model/pom.xml
  daikon-messages/pom.xml
  daikon-multitenant/multitenant-core/pom.xml
  daikon-multitenant/multitenant-spring-async/pom.xml
  daikon-multitenant/multitenant-spring-web/pom.xml
  daikon-multitenant/pom.xml
  daikon-service/pom.xml
  daikon-service/service-common/pom.xml
  daikon-service/service-docs/pom.xml
  daikon-service/service-examples/dashboard-service/pom.xml
  daikon-service/service-examples/pom.xml
  daikon-service/service-examples/weather-service/pom.xml
  daikon-service/service-parent/pom.xml
  daikon-spring/daikon-spring-mongo/pom.xml
  daikon-spring/daikon-spring-security/pom.xml
  daikon-spring/daikon-spring-tenancy/pom.xml
  daikon-spring/daikon-spring-utils/pom.xml
  daikon-spring/pom.xml
  daikon-tql/daikon-tql-bean/pom.xml
  daikon-tql/daikon-tql-core/pom.xml
  daikon-tql/daikon-tql-mongo/pom.xml
  daikon-tql/pom.xml
  daikon/pom.xml
  pom.xml
  reporting/pom.xml
Labels: Merged build passed

#355 fix: Additional fixes for TQL
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/parser/TqlExpressionVisitor.java
  daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/TestTqlParser_AllFields.java
Labels: Can be merged, Merged build passed
