Repository Talend/daikon, pull requests merged in 2018-09, with the labels that each got.

#393 feat(TDQ-15761): Translate word patterns into mongo/regex patterns
  daikon/src/main/java/org/talend/daikon/pattern/word/WordPattern.java
  daikon/src/main/java/org/talend/daikon/pattern/word/WordPatternToRegex.java
  daikon/src/main/java/org/talend/daikon/pattern/word/WordPatternToRegexConstants.java
  daikon/src/test/java/org/talend/daikon/pattern/word/WordPatternToRegexTest.java
Labels: Merged build passed

#388 Kjwang/feat tup 20282 job signature and verification
  daikon-signature-verifier/README.md
  daikon-signature-verifier/pom.xml
  daikon-signature-verifier/src/main/java/org/talend/daikon/signature/exceptions/InvalidKeyStoreException.java
  daikon-signature-verifier/src/main/java/org/talend/daikon/signature/exceptions/MissingEntryException.java
  daikon-signature-verifier/src/main/java/org/talend/daikon/signature/exceptions/NoCodeSignCertificateException.java
  daikon-signature-verifier/src/main/java/org/talend/daikon/signature/exceptions/NoValidCertificateException.java
  daikon-signature-verifier/src/main/java/org/talend/daikon/signature/exceptions/UnsignedArchiveException.java
  daikon-signature-verifier/src/main/java/org/talend/daikon/signature/exceptions/UnsignedEntryException.java
  daikon-signature-verifier/src/main/java/org/talend/daikon/signature/exceptions/VerifyException.java
  daikon-signature-verifier/src/main/java/org/talend/daikon/signature/exceptions/VerifyFailedException.java
  daikon-signature-verifier/src/main/java/org/talend/daikon/signature/keystore/KeyStoreManager.java
  daikon-signature-verifier/src/main/java/org/talend/daikon/signature/verify/ZipVerifier.java
  daikon-signature-verifier/src/test/java/org/talend/daikon/signature/verify/ZipVerifierTest.java
  pom.xml
Labels: Merged build passed

#392 feat(TDS-2681): add wordComplies operator to TQL to distinguish patte…
  daikon-tql/daikon-tql-bean/pom.xml
  daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/BeanPredicateVisitor.java
  daikon-tql/daikon-tql-bean/src/test/java/org/talend/tql/bean/BeanPredicateVisitorTest.java
  daikon-tql/daikon-tql-client/README.md
  daikon-tql/daikon-tql-client/src/converter/operators/__tests__/containsIgnoreCase.spec.js
  daikon-tql/daikon-tql-client/src/converter/operators/__tests__/wordComplies.spec.js
  daikon-tql/daikon-tql-client/src/converter/operators/containsIgnoreCase.js
  daikon-tql/daikon-tql-client/src/converter/operators/index.js
  daikon-tql/daikon-tql-client/src/converter/operators/wordComplies.js
  daikon-tql/daikon-tql-core/src/main/antlr4/TqlLexer.g4
  daikon-tql/daikon-tql-core/src/main/antlr4/TqlParser.g4
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/api/TqlBuilder.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldWordCompliesPattern.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/parser/TqlExpressionVisitor.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/visitor/IASTVisitor.java
  daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/TestTqlParser_WordComply.java
  daikon-tql/daikon-tql-core/src/test/java/org/talend/tql/api/TestTqlApi_WordComply.java
  daikon-tql/daikon-tql-mongo/pom.xml
  daikon-tql/daikon-tql-mongo/src/main/java/org/talend/tqlmongo/ASTVisitor.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_WordComply.java
  daikon/src/main/java/org/talend/daikon/pattern/word/WordPatternToRegex.java
  daikon/src/test/java/org/talend/daikon/pattern/word/WordPatternToRegexTest.java
Labels: Merged build passed

#394 fix(TDP-4404): missing tql javascript listener
  README.md
  daikon-tql/README.md
  daikon-tql/daikon-tql-client/src/converter/__tests__/parser.spec.js
  daikon-tql/daikon-tql-client/src/converter/parser.js
  daikon-tql/daikon-tql-core/src/main/resources/tql/index.js
  daikon-tql/pom.xml
Labels: Frontend, Merged build passed, Reviewing

#395 feat(TDQ-15761): Adapt word-based patterns and regexes
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_WordComply.java
  daikon/src/main/java/org/talend/daikon/pattern/word/WordPatternToRegexConstants.java
  daikon/src/test/java/org/talend/daikon/pattern/word/WordPatternToRegexTest.java
Labels: Merged build passed, Need review

#396 feat(TDS-2681): Add tests.
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_WordComply.java
Labels: Merged build passed

#397 feat(TDQ-15793): Computation of the regexes corresponding to a char p…
  daikon/src/main/java/org/talend/daikon/pattern/PatternRegexUtils.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPattern.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegex.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegexConstants.java
  daikon/src/main/java/org/talend/daikon/pattern/word/WordPatternToRegex.java
  daikon/src/main/java/org/talend/daikon/pattern/word/WordPatternToRegexConstants.java
  daikon/src/test/java/org/talend/daikon/pattern/character/CharPatternToRegexTest.java
Labels: Merged build passed, Need review

#400 feat(TDQ-15793): Factorize charPattern regexes
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegex.java
  daikon/src/test/java/org/talend/daikon/pattern/character/CharPatternToRegexTest.java
Labels: Merged build passed

#402 feat(TDQ-15748): use TDQ tool in bean predicate visitor
  daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/BeanPredicateVisitor.java
Labels: Merged build passed, Need review

#398 feat(2681): Correct incompatibility between mongo and Fongo for regex…
  daikon-tql/README.md
  daikon-tql/daikon-tql-mongo/README.md
  daikon-tql/daikon-tql-mongo/src/main/java/org/talend/tqlmongo/ASTVisitor.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Abstract.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_WordComply.java
Labels: Merged build passed

#404 feat(TDS-2682): escape '/' for javascript.
  daikon/src/main/java/org/talend/daikon/pattern/PatternRegexUtils.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegex.java
  daikon/src/test/java/org/talend/daikon/pattern/character/CharPatternToRegexTest.java
Labels: Merged build passed
