Repository Talend/daikon, pull requests merged in 2018-02, with the labels that each got.

#337 fix(TDI-40061): avoid to reset the url factory
  daikon/src/main/java/org/talend/daikon/runtime/RuntimeUtil.java
  daikon/src/test/java/org/talend/daikon/runtime/RuntimeUtilTest.java
Labels: Merged build passed

#340 fix(TMDM-11854): Output with keywords fields names
  daikon/src/main/java/org/talend/daikon/avro/AvroNamesValidationHelper.java
  daikon/src/test/java/org/talend/daikon/avro/AvroNamesValidationHelperTest.java
Labels: Merged build passed, Need review

#331 Daikon logging request interceptor
  daikon-logging/logging-kafka-interceptor/README.adoc
  daikon-logging/logging-kafka-interceptor/pom.xml
  daikon-logging/logging-kafka-interceptor/src/integrationTest/java/org/talend/daikon/logging/kafka/EmbeddedZookeeper.java
  daikon-logging/logging-kafka-interceptor/src/integrationTest/java/org/talend/daikon/logging/kafka/FreeRandomPort.java
  daikon-logging/logging-kafka-interceptor/src/integrationTest/java/org/talend/daikon/logging/kafka/KafkaBroker.java
  daikon-logging/logging-kafka-interceptor/src/integrationTest/java/org/talend/daikon/logging/kafka/KafkaGenericConsumer.java
  daikon-logging/logging-kafka-interceptor/src/integrationTest/java/org/talend/daikon/logging/kafka/KafkaUnit.java
  daikon-logging/logging-kafka-interceptor/src/integrationTest/java/org/talend/daikon/logging/kafka/KafkaUnitAdmin.java
  daikon-logging/logging-kafka-interceptor/src/integrationTest/resources/logback-test.xml
  daikon-logging/logging-kafka-interceptor/src/main/java/org/talend/daikon/logging/TalendKafkaConsumerInterceptor.java
  daikon-logging/logging-kafka-interceptor/src/main/java/org/talend/daikon/logging/TalendKafkaProducerInterceptor.java
  daikon-logging/logging-kafka-interceptor/src/test/java/org/talend/daikon/logging/kafka/ConsumerInterceptorsTest.java
  daikon-logging/logging-kafka-interceptor/src/test/java/org/talend/daikon/logging/kafka/ProducerInterceptorsTest.java
  daikon-logging/logging-kafka-interceptor/src/test/resources/logback-test.xml
  daikon-logging/logging-request-interceptor/README.adoc
  daikon-logging/logging-request-interceptor/pom.xml
  daikon-logging/logging-request-interceptor/src/main/java/org/talend/daikon/logging/TalendFeignRequestInterceptor.java
  daikon-logging/logging-request-interceptor/src/main/java/org/talend/daikon/logging/TalendRestRequestInterceptor.java
  daikon-logging/logging-request-interceptor/src/main/java/org/talend/daikon/logging/TraceRequestUtil.java
  daikon-logging/logging-request-interceptor/src/test/java/org/talend/daikon/logging/FeignRequestInterceptorTest.java
  daikon-logging/logging-request-interceptor/src/test/java/org/talend/daikon/logging/RestTemplateRequestInterceptorTest.java
  daikon-logging/logging-request-interceptor/src/test/resources/logback-test.xml
  daikon-logging/pom.xml
Labels: Merged build passed, Work in progress(do not merge)

#339 feat(TFD-2986): Add uncollapsible nested and columns properties.
  daikon/src/main/java/org/talend/daikon/properties/presentation/Widget.java
  daikon/src/main/java/org/talend/daikon/serialize/jsonschema/UiSchemaConstants.java
  daikon/src/main/java/org/talend/daikon/serialize/jsonschema/mapping/FieldMapper.java
  daikon/src/main/java/org/talend/daikon/serialize/jsonschema/mapping/NestedPropertiesFieldMapper.java
  daikon/src/test/java/org/talend/daikon/serialize/jsonschema/ColumnProperties.java
  daikon/src/test/java/org/talend/daikon/serialize/jsonschema/UiSchemaGeneratorTest.java
  daikon/src/test/java/org/talend/daikon/serialize/jsonschema/UncollapsageNestedProperties.java
Labels: Merged build passed

#341 Update Logging Kafka Unit tests to use byte[] for the message
  daikon-logging/logging-kafka-interceptor/src/test/java/org/talend/daikon/logging/kafka/ConsumerInterceptorsTest.java
  daikon-logging/logging-kafka-interceptor/src/test/java/org/talend/daikon/logging/kafka/ProducerInterceptorsTest.java
Labels: Merged build passed
