Repository Talend/daikon, pull requests merged in 2019-06, with the labels that each got.

#506 feat(TDKN-244): Allow to custom add token protected endpoints
  daikon-spring/daikon-spring-examples/daikon-spring-example-security/README.adoc
  daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/java/org/talend/demo/actuator/ActuatorDemoController.java
  daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/java/org/talend/demo/actuator/SecurityConfiguration.java
  daikon-spring/daikon-spring-security/README.adoc
  daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenProtectedPath.java
  daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java
Labels: Merged build passed

#501 fix(TDI-42071): avoid the warn : No context given for ch.qos.logback.core.encoder.LayoutWrappingEncoder
  daikon-audit/audit-logback/src/main/java/org/talend/logging/audit/logback/LogbackConfigurer.java
Labels: Merged build passed

#507 feat(TDKN-245): Add ability to hide host information in appenders
  daikon-logging/logging-event-layout/README.MD
  daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/Log4j2JSONLayout.java
  daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/Log4jJSONLayout.java
  daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/LogbackJSONLayout.java
  daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/Log4j2JSONLayoutTest.java
  daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/Log4jJSONLayoutTest.java
Labels: Merged build failed, Work in progress(do not merge)

#509 feat(): make LocalResourceResolver public
  daikon-spring/daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalResourceResolver.java
Labels: Merged build passed

#510 feat(): make LocalResourceResolver public
  daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalDeletableResource.java
  daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalResourceResolver.java
Labels: Merged build passed

#511 feat(): make LocalDeletableResource public
  daikon-spring/daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalDeletableResource.java
Labels: Merged build failed

#508 Adding a new KeySource implementation for pbkdf2
  daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/KeySources.java
  daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/digest/DigestSources.java
  daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/CipherSourcesTest.java
  daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/KeySourcesTest.java
Labels: Merged build passed

#512 feat(TDKN-245): Allow host info configuration from code
  daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AuditConfiguration.java
  daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AuditConfigurationTest.java
  daikon-audit/audit-common/src/test/resources/test.audit.properties
  daikon-audit/audit-log4j1/src/main/java/org/talend/logging/audit/log4j1/Log4j1Configurer.java
  daikon-audit/audit-logback/src/main/java/org/talend/logging/audit/logback/LogbackConfigurer.java
Labels: Merged build failed

#514 chore(build): Build fixes for 1.4.0 build
  daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/KeySourcesTest.java
  daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/Log4j2JSONLayoutTest.java
  daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java
Labels: Merged build passed

#516 fix(logs): Make the KeyValuePair per logger
  daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/Log4j2JSONLayout.java
  daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/Log4j2JSONLayoutTest.java
  daikon-logging/logging-event-layout/src/test/resources/log4j2.xml
Labels: Merged build passed

#517 chore(TDKN-247/logs: Bump log4j2 version to 2.11.2
  daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/Log4j2JSONLayout.java
  pom.xml
Labels: Merged build passed
