Repository Talend/daikon, pull requests merged in 2019-05, with the labels that each got.

#485 add project name as optional parameter in the documentation
  daikon-documentation/src/main/java/org/talend/daikon/ReleaseNotes.java
Labels: Merged build passed

#483 fix(TDKN-233): manage more use cases in BigDecimalParser
  daikon/src/main/java/org/talend/daikon/number/BigDecimalParser.java
  daikon/src/test/java/org/talend/daikon/number/BigDecimalParserTest.java
Labels: Merged build passed, Need review

#486 fix(TDKN-233): manage more use cases in BigDecimalParser (#483)
  daikon/src/main/java/org/talend/daikon/number/BigDecimalParser.java
  daikon/src/test/java/org/talend/daikon/number/BigDecimalParserTest.java
Labels: Merged build passed, Need review

#489 TDKN-237 Provide getDefault() method for class org.talend.daikon.security.CryptoHelper on branch maintenance/0.31
  daikon/src/main/java/org/talend/daikon/security/CryptoHelper.java
Labels: Merged build passed

#488 chore(TDS-3833): make daikon tql compatible with spring data mongodb 2
  daikon-spring/daikon-content-service/content-service-journal-mongo/pom.xml
  daikon-tql/daikon-tql-mongo/pom.xml
  daikon-tql/daikon-tql-mongo/src/main/java/org/talend/tqlmongo/ASTVisitor.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Abstract.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Between.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Boolean.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Complex.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Comply.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Contain.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_ContainsIgnoreCase.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Decimal.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_FieldComparison.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_In.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Integer.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Match.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Not.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_WordComply.java
  pom.xml
Labels: Merged build passed

#490 feat(TDKN-238): Allow unauthenticated access to Prometheus
  daikon-spring/daikon-spring-examples/daikon-spring-example-security/README.adoc
  daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/resources/application-public-prometheus.properties
  daikon-spring/daikon-spring-security/README.adoc
  daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java
Labels: Merged build passed, Need review

#492 feat(TDKN-238): Allow public access to /health
  daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java
Labels: Merged build passed, Need review

#493 feat(TDC-2245): make BeanPredicateVisitor more extendable
  daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/BeanPredicateVisitor.java
  daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/DefaultLanguageBinder.java
  daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/LanguageBinder.java
  daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/MethodAccessor.java
  daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/MethodAccessorFactory.java
Labels: Merged build passed

#494 workItem(TDQ-14200) : add blowfish encryption method
  daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/CipherSources.java
  daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/CipherSourcesTest.java
Labels: Merged build passed

#495 fix(TDKN-240): Upgrade dependencies
  daikon-spring/daikon-content-service/s3-content-service/pom.xml
  daikon-spring/daikon-spring-metrics/pom.xml
  pom.xml
Labels: Merged build passed

#497 chore(TDKN-241) Upgrade to Spring Boot 2.1.4
  daikon-tql/daikon-tql-mongo/pom.xml
  daikon-tql/daikon-tql-mongo/src/main/java/org/talend/tqlmongo/ASTVisitor.java
  pom.xml
Labels: Merged build passed

#496 fix(TDKN-238): disabled csrf for spring security
  daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java
Labels: Merged build passed

#484 chore(TDKN-239): Add Digester to crypto-utils
  daikon-crypto/crypto-utils/README.md
  daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/CipherSources.java
  daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/EncodingUtils.java
  daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/KeySources.java
  daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/digest/DigestSource.java
  daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/digest/DigestSources.java
  daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/digest/Digester.java
  daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/digest/DigestSourcesTest.java
  daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/digest/DigesterTest.java
Labels: Merged build failed

#498 chore(TDKN-241): Upgrade Spring Boot version for examples.
  daikon-spring/daikon-spring-examples/pom.xml
Labels: Merged build passed

#502 fix(TDKN-242) update jackson version to 2.9.8
  pom.xml
Labels: Merged build passed

#503 fix(TDKN-242) update jackson version to 2.9.9
  pom.xml
Labels: Merged build passed

#504 fix(TDKN-242) update jackson version to 2.9.9
  pom.xml
Labels: Merged build passed

#499 feat(TDQ-14200) : add CBC mode to Blowfish encryption
  daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/CipherSources.java
  daikon-crypto/crypto-utils/src/test/java/org/talend/daikon/crypto/CipherSourcesTest.java
Labels: Merged build passed

#505 Remove unused dependencies from compile scope
  daikon-crypto/daikon-signature-verifier/pom.xml
Labels: Merged build passed
