Repository Talend/daikon, pull requests merged in 2019-02, with the labels that each got.

#446 Removing duplicate dependency
  daikon-scala/dynamic-log/dynamic-log-web-play/pom.xml
Labels: Merged build passed

#447 feat(TDQ-16481): Split Latin in characters pattern (#438)
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPattern.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegex.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegexConstants.java
  daikon/src/test/java/org/talend/daikon/pattern/character/CharPatternToRegexTest.java
Labels: Merged build passed

#448 release: prepare release daikon-0.28.1
  daikon-audit/audit-all/pom.xml
  daikon-audit/audit-common/pom.xml
  daikon-audit/audit-log4j1/pom.xml
  daikon-audit/audit-logback/pom.xml
  daikon-audit/pom.xml
  daikon-content-service/content-service-common/pom.xml
  daikon-content-service/content-service-journal-mongo/pom.xml
  daikon-content-service/content-service-journal/pom.xml
  daikon-content-service/local-content-service/pom.xml
  daikon-content-service/pom.xml
  daikon-content-service/s3-content-service/pom.xml
  daikon-i18n/pom.xml
  daikon-logging/logging-event-layout/pom.xml
  daikon-logging/logging-http-headers/pom.xml
  daikon-logging/logging-kafka-interceptor/pom.xml
  daikon-logging/logging-request-interceptor/pom.xml
  daikon-logging/logging-spring-security/pom.xml
  daikon-logging/pom.xml
  daikon-messages/messages-demo/demo-listener/pom.xml
  daikon-messages/messages-demo/demo-producer/pom.xml
  daikon-messages/messages-demo/pom.xml
  daikon-messages/messages-model-spring-support/pom.xml
  daikon-messages/messages-model/pom.xml
  daikon-messages/pom.xml
  daikon-multitenant/multitenant-core/pom.xml
  daikon-multitenant/multitenant-spring-async/pom.xml
  daikon-multitenant/multitenant-spring-web/pom.xml
  daikon-multitenant/pom.xml
  daikon-service/pom.xml
  daikon-service/service-common/pom.xml
  daikon-service/service-docs/pom.xml
  daikon-service/service-examples/dashboard-service/pom.xml
  daikon-service/service-examples/pom.xml
  daikon-service/service-examples/weather-service/pom.xml
  daikon-service/service-parent/pom.xml
  daikon-signature-verifier/pom.xml
  daikon-spring/daikon-spring-mongo/pom.xml
  daikon-spring/daikon-spring-security/pom.xml
  daikon-spring/daikon-spring-tenancy/pom.xml
  daikon-spring/daikon-spring-utils/pom.xml
  daikon-spring/daikon-spring-zipkin/pom.xml
  daikon-spring/pom.xml
  daikon-tql/daikon-tql-bean/pom.xml
  daikon-tql/daikon-tql-core/pom.xml
  daikon-tql/daikon-tql-mongo/pom.xml
  daikon-tql/pom.xml
  daikon/pom.xml
  pom.xml
  reporting/pom.xml
Labels: Merged build passed

#449 release: prepare for next development iteration
  daikon-audit/audit-all/pom.xml
  daikon-audit/audit-common/pom.xml
  daikon-audit/audit-log4j1/pom.xml
  daikon-audit/audit-logback/pom.xml
  daikon-audit/pom.xml
  daikon-content-service/content-service-common/pom.xml
  daikon-content-service/content-service-journal-mongo/pom.xml
  daikon-content-service/content-service-journal/pom.xml
  daikon-content-service/local-content-service/pom.xml
  daikon-content-service/pom.xml
  daikon-content-service/s3-content-service/pom.xml
  daikon-i18n/pom.xml
  daikon-logging/logging-event-layout/pom.xml
  daikon-logging/logging-http-headers/pom.xml
  daikon-logging/logging-kafka-interceptor/pom.xml
  daikon-logging/logging-request-interceptor/pom.xml
  daikon-logging/logging-spring-security/pom.xml
  daikon-logging/pom.xml
  daikon-messages/messages-demo/demo-listener/pom.xml
  daikon-messages/messages-demo/demo-producer/pom.xml
  daikon-messages/messages-demo/pom.xml
  daikon-messages/messages-model-spring-support/pom.xml
  daikon-messages/messages-model/pom.xml
  daikon-messages/pom.xml
  daikon-multitenant/multitenant-core/pom.xml
  daikon-multitenant/multitenant-spring-async/pom.xml
  daikon-multitenant/multitenant-spring-web/pom.xml
  daikon-multitenant/pom.xml
  daikon-service/pom.xml
  daikon-service/service-common/pom.xml
  daikon-service/service-docs/pom.xml
  daikon-service/service-examples/dashboard-service/pom.xml
  daikon-service/service-examples/pom.xml
  daikon-service/service-examples/weather-service/pom.xml
  daikon-service/service-parent/pom.xml
  daikon-signature-verifier/pom.xml
  daikon-spring/daikon-spring-mongo/pom.xml
  daikon-spring/daikon-spring-security/pom.xml
  daikon-spring/daikon-spring-tenancy/pom.xml
  daikon-spring/daikon-spring-utils/pom.xml
  daikon-spring/daikon-spring-zipkin/pom.xml
  daikon-spring/pom.xml
  daikon-tql/daikon-tql-bean/pom.xml
  daikon-tql/daikon-tql-core/pom.xml
  daikon-tql/daikon-tql-mongo/pom.xml
  daikon-tql/pom.xml
  daikon/pom.xml
  pom.xml
  reporting/pom.xml
Labels: Merged build passed

#452 WorkItem(TDKN-213):Daikon exception is not an OSGI plugin (#432)
  daikon-exception/pom.xml
Labels: Reviewing

#453 chore: next dev iteration 0.29.1-SNAPSHOT
  daikon-audit/audit-all/pom.xml
  daikon-audit/audit-common/pom.xml
  daikon-audit/audit-log4j1/pom.xml
  daikon-audit/audit-logback/pom.xml
  daikon-audit/pom.xml
  daikon-content-service/content-service-common/pom.xml
  daikon-content-service/content-service-journal-mongo/pom.xml
  daikon-content-service/content-service-journal/pom.xml
  daikon-content-service/local-content-service/pom.xml
  daikon-content-service/pom.xml
  daikon-content-service/s3-content-service/pom.xml
  daikon-i18n/pom.xml
  daikon-logging/logging-event-layout/pom.xml
  daikon-logging/logging-http-headers/pom.xml
  daikon-logging/logging-kafka-interceptor/pom.xml
  daikon-logging/logging-request-interceptor/pom.xml
  daikon-logging/logging-spring-security/pom.xml
  daikon-logging/pom.xml
  daikon-messages/messages-demo/demo-listener/pom.xml
  daikon-messages/messages-demo/demo-producer/pom.xml
  daikon-messages/messages-demo/pom.xml
  daikon-messages/messages-model-spring-support/pom.xml
  daikon-messages/messages-model/pom.xml
  daikon-messages/pom.xml
  daikon-multitenant/multitenant-core/pom.xml
  daikon-multitenant/multitenant-spring-async/pom.xml
  daikon-multitenant/multitenant-spring-web/pom.xml
  daikon-multitenant/pom.xml
  daikon-service/pom.xml
  daikon-service/service-common/pom.xml
  daikon-service/service-docs/pom.xml
  daikon-service/service-examples/dashboard-service/pom.xml
  daikon-service/service-examples/pom.xml
  daikon-service/service-examples/weather-service/pom.xml
  daikon-service/service-parent/pom.xml
  daikon-signature-verifier/pom.xml
  daikon-spring/daikon-spring-mongo/pom.xml
  daikon-spring/daikon-spring-security/pom.xml
  daikon-spring/daikon-spring-tenancy/pom.xml
  daikon-spring/daikon-spring-utils/pom.xml
  daikon-spring/daikon-spring-zipkin/pom.xml
  daikon-spring/pom.xml
  daikon-tql/daikon-tql-bean/pom.xml
  daikon-tql/daikon-tql-core/pom.xml
  daikon-tql/daikon-tql-mongo/pom.xml
  daikon-tql/pom.xml
  daikon/pom.xml
  pom.xml
  reporting/pom.xml
Labels: Merged build passed

#450 feat(TDQ-16481): Split Latin in characters pattern
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPattern.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegex.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegexConstants.java
  daikon/src/test/java/org/talend/daikon/pattern/character/CharPatternToRegexTest.java
Labels: Merged build passed

#454 chore(build): Allow release from branches
  Jenkinsfile
Labels: Merged build passed

#458 chore(TDKN-217): Add token based authentication support
  daikon-spring/daikon-spring-examples/daikon-spring-example-security/README.adoc
  daikon-spring/daikon-spring-examples/daikon-spring-example-security/pom.xml
  daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/java/org/talend/demo/actuator/ActuatorApplication.java
  daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/java/org/talend/demo/actuator/ActuatorDemoController.java
  daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/java/org/talend/demo/actuator/SecurityConfiguration.java
  daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/resources/application-notoken.properties
  daikon-spring/daikon-spring-examples/daikon-spring-example-security/src/main/resources/application-token.properties
  daikon-spring/daikon-spring-examples/pom.xml
  daikon-spring/daikon-spring-security/README.adoc
  daikon-spring/daikon-spring-security/pom.xml
  daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/access/AccessDeniedDefaults.java
  daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/access/RequiresAuthority.java
  daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/access/RequiresAuthorityAspect.java
  daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/NoConfiguredTokenFilter.java
  daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenAuthentication.java
  daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenAuthenticationFilter.java
  daikon-spring/daikon-spring-security/src/main/java/org/talend/daikon/security/token/TokenSecurityConfiguration.java
  daikon-spring/daikon-spring-security/src/main/resources/META-INF/spring.factories
  daikon-spring/daikon-spring-security/src/test/java/org/talend/daikon/security/access/RequiresAuthorityAspectTest.java
  daikon-spring/daikon-spring-security/src/test/java/org/talend/daikon/security/token/NoConfiguredTokenFilterTest.java
  daikon-spring/daikon-spring-security/src/test/java/org/talend/daikon/security/token/TokenAuthenticationFilterTest.java
  daikon-spring/daikon-spring-security/src/test/java/org/talend/daikon/security/token/TokenAuthenticationTest.java
  daikon-spring/pom.xml
Labels: Merged build failed, Need review

#425 feat(TDKN-208): Add support for Minio authentication
  daikon-spring/daikon-content-service/s3-content-service/README.md
  daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/IncorrectS3ConfigurationAnalyzer.java
  daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ContentServiceConfiguration.java
  daikon-spring/daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/AmazonS3TestWrapper.java
  daikon-spring/daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/S3ContentServiceConfigurationTest.java
  daikon-spring/daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/S3DeletableResourceTest.java
  daikon-spring/daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/TestConfiguration.java
Labels: Merged build passed, Reviewing

#367 fix(TDKN-198): Add support for list match in TQL -> BeanPredicate
  daikon-tql/daikon-tql-bean/pom.xml
  daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/BeanPredicateVisitor.java
  daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/IterableMethodAccessor.java
  daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/MethodAccessor.java
  daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/MethodAccessorFactory.java
  daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/UnaryMethodAccessor.java
  daikon-tql/daikon-tql-bean/src/test/java/org/talend/tql/bean/BeanPredicateVisitorTest.java
Labels: Can be merged, Merged build passed

#461 chore(TDKN-211): Add release notes
  Jenkinsfile
  daikon-documentation/pom.xml
  daikon-documentation/src/main/java/org/talend/daikon/ReleaseNotes.java
  daikon-documentation/src/test/java/org/talend/daikon/ReleaseNotesTest.java
  daikon-documentation/src/test/resources/project-to-test/pom.xml
  pom.xml
  releases/pom.xml
Labels: Merged build passed, Need review

#456 Fix readme about log correlation and custom fields
  daikon-logging/logging-event-layout/README.MD
Labels: Merged build passed

#460 [TDKN-218] Ensure a missing SUN_BOOT_CLASS_PATH does not lead to a NPE in SunOracleStandardPropertiesStrategy
  daikon/src/main/java/org/talend/daikon/sandbox/properties/SunOracleStandardPropertiesStrategy.java
Labels: Merged build passed

#421 chore(TDKN-220) make audit context immutable
  daikon-audit/audit-common/src/main/java/org/talend/logging/audit/Context.java
  daikon-audit/audit-common/src/main/java/org/talend/logging/audit/ContextBuilder.java
  daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/DefaultContextImpl.java
  daikon-audit/audit-common/src/test/java/org/talend/logging/audit/ContextBuilderTest.java
Labels: Merged build passed

#463 doc(TQL): Update client readme
  daikon-tql/daikon-tql-client/README.md
Labels: Merged build passed
