Repository Talend/daikon, pull requests merged in 2019-01, with the labels that each got.

#428 fix(TDKN-209): Add a deterministic hash to the avro schema name.
  daikon/src/main/java/org/talend/daikon/avro/inferrer/JsonSchemaInferrer.java
  daikon/src/test/java/org/talend/daikon/avro/inferrer/JsonSchemaInferrerTest.java
Labels: Merged build passed

#429 chore(TDKN-210): Add release notification
  Jenkinsfile
Labels: Merged build passed

#430 bugfix(TUP-21205):Remove CryptoHelper from tcommon-studio-se + tcommo…
  daikon/src/main/java/org/talend/daikon/security/CryptoHelper.java
Labels: Merged build passed

#432 WorkItem(TDKN-213):Daikon exception is not an OSGI plugin
  daikon-exception/pom.xml
Labels: Merged build passed

#435 feat(TFD-6171) : add kafka headers support
  daikon-messages/messages-model/pom.xml
  daikon-messages/messages-model/src/main/java/org/talend/daikon/messages/utils/HeadersUtils.java
Labels: Merged build passed

#437 release: prepare for next development iteration 0.31.1-SNAPSHOT
  daikon-audit/audit-all/pom.xml
  daikon-audit/audit-common/pom.xml
  daikon-audit/audit-log4j1/pom.xml
  daikon-audit/audit-logback/pom.xml
  daikon-audit/pom.xml
  daikon-content-service/content-service-common/pom.xml
  daikon-content-service/content-service-journal-mongo/pom.xml
  daikon-content-service/content-service-journal/pom.xml
  daikon-content-service/local-content-service/pom.xml
  daikon-content-service/pom.xml
  daikon-content-service/s3-content-service/pom.xml
  daikon-exception/pom.xml
  daikon-i18n/pom.xml
  daikon-logging/logging-event-layout/pom.xml
  daikon-logging/logging-http-headers/pom.xml
  daikon-logging/logging-kafka-interceptor/pom.xml
  daikon-logging/logging-request-interceptor/pom.xml
  daikon-logging/logging-spring-security/pom.xml
  daikon-logging/pom.xml
  daikon-messages/messages-demo/demo-listener/pom.xml
  daikon-messages/messages-demo/demo-producer/pom.xml
  daikon-messages/messages-demo/pom.xml
  daikon-messages/messages-model-spring-support/pom.xml
  daikon-messages/messages-model/pom.xml
  daikon-messages/pom.xml
  daikon-multitenant/multitenant-core/pom.xml
  daikon-multitenant/multitenant-spring-async/pom.xml
  daikon-multitenant/multitenant-spring-web/pom.xml
  daikon-multitenant/pom.xml
  daikon-scala/dynamic-log/pom.xml
  daikon-scala/pom.xml
  daikon-scala/scala-parent/pom.xml
  daikon-scala/scala-play2-dependencies/pom.xml
  daikon-service/pom.xml
  daikon-service/service-common/pom.xml
  daikon-service/service-docs/pom.xml
  daikon-service/service-examples/dashboard-service/pom.xml
  daikon-service/service-examples/pom.xml
  daikon-service/service-examples/weather-service/pom.xml
  daikon-service/service-parent/pom.xml
  daikon-signature-verifier/pom.xml
  daikon-spring/daikon-spring-mongo/pom.xml
  daikon-spring/daikon-spring-security/pom.xml
  daikon-spring/daikon-spring-tenancy/pom.xml
  daikon-spring/daikon-spring-utils/pom.xml
  daikon-spring/daikon-spring-zipkin/pom.xml
  daikon-spring/pom.xml
  daikon-tql/daikon-tql-bean/pom.xml
  daikon-tql/daikon-tql-core/pom.xml
  daikon-tql/daikon-tql-mongo/pom.xml
  daikon-tql/pom.xml
  daikon/pom.xml
  pom.xml
  reporting/pom.xml
Labels: Merged build passed, Need review

#436 TDKN-214 - Update Jackson
  pom.xml
Labels: Merged build passed

#440 DEVOPS-6085 Fix Jenkins pipeline for PR builds
  Jenkinsfile
Labels: Merged build passed

#441 Use 64-bit Maven builder image (reqd by content-service-journal-mongo)
  Jenkinsfile
Labels: Merged build failed

#443 Added repository webhook, remove polling
  Jenkinsfile
Labels: Merged build passed

#445 feat(TDQ-16481): Split Latin in characters pattern (#438)
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPattern.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegex.java
  daikon/src/main/java/org/talend/daikon/pattern/character/CharPatternToRegexConstants.java
  daikon/src/test/java/org/talend/daikon/pattern/character/CharPatternToRegexTest.java
Labels: Can be merged, Merged build passed
