Repository Talend/daikon, pull requests merged in 2019-03, with the labels that each got.

#465 fix Readme links
  README.md
Labels: Merged build passed

#462 feat(TDKN-219) Add daikon-spring-metrics
  daikon-spring/daikon-content-service/content-service-journal-mongo/pom.xml
  daikon-spring/daikon-content-service/pom.xml
  daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ContentServiceConfiguration.java
  daikon-spring/daikon-content-service/s3-content-service/src/test/java/org/talend/daikon/content/s3/AmazonS3TestWrapper.java
  daikon-spring/daikon-spring-examples/daikon-spring-example-metrics/README.adoc
  daikon-spring/daikon-spring-examples/daikon-spring-example-metrics/assets/images/nested_method_calls.png
  daikon-spring/daikon-spring-examples/daikon-spring-example-metrics/pom.xml
  daikon-spring/daikon-spring-examples/daikon-spring-example-metrics/src/main/java/org/talend/demo/MetricsApplication.java
  daikon-spring/daikon-spring-examples/daikon-spring-example-metrics/src/main/java/org/talend/demo/MetricsDemoController.java
  daikon-spring/daikon-spring-examples/daikon-spring-example-metrics/src/main/java/org/talend/demo/SecurityConfiguration.java
  daikon-spring/daikon-spring-examples/daikon-spring-example-metrics/src/main/java/org/talend/demo/SubWorker.java
  daikon-spring/daikon-spring-examples/daikon-spring-example-metrics/src/main/java/org/talend/demo/Worker.java
  daikon-spring/daikon-spring-examples/daikon-spring-example-metrics/src/main/resources/application.properties
  daikon-spring/daikon-spring-examples/daikon-spring-example-security/pom.xml
  daikon-spring/daikon-spring-examples/pom.xml
  daikon-spring/daikon-spring-metrics/README.adoc
  daikon-spring/daikon-spring-metrics/pom.xml
  daikon-spring/daikon-spring-metrics/src/main/java/org/talend/daikon/spring/metrics/VolumeMetered.java
  daikon-spring/daikon-spring-metrics/src/main/java/org/talend/daikon/spring/metrics/config/Aspects.java
  daikon-spring/daikon-spring-metrics/src/main/java/org/talend/daikon/spring/metrics/config/MetricsConfiguration.java
  daikon-spring/daikon-spring-metrics/src/main/java/org/talend/daikon/spring/metrics/io/Metered.java
  daikon-spring/daikon-spring-metrics/src/main/java/org/talend/daikon/spring/metrics/io/MeteredInputStream.java
  daikon-spring/daikon-spring-metrics/src/main/java/org/talend/daikon/spring/metrics/io/MeteredOutputStream.java
  daikon-spring/daikon-spring-metrics/src/main/java/org/talend/daikon/spring/metrics/io/PartWrapper.java
  daikon-spring/daikon-spring-metrics/src/main/java/org/talend/daikon/spring/metrics/io/ReleasableInputStream.java
  daikon-spring/daikon-spring-metrics/src/main/java/org/talend/daikon/spring/metrics/io/ReleasableOutputStream.java
  daikon-spring/daikon-spring-metrics/src/main/java/org/talend/daikon/spring/metrics/io/SpanOutputStream.java
  daikon-spring/daikon-spring-metrics/src/main/resources/META-INF/spring.factories
  daikon-spring/daikon-spring-metrics/src/test/java/org/talend/daikon/spring/metrics/config/AspectsTimeTest.java
  daikon-spring/daikon-spring-metrics/src/test/java/org/talend/daikon/spring/metrics/config/AspectsVolumeTest.java
  daikon-spring/daikon-spring-metrics/src/test/java/org/talend/daikon/spring/metrics/io/MeteredInputStreamTest.java
  daikon-spring/daikon-spring-metrics/src/test/java/org/talend/daikon/spring/metrics/io/MeteredOutputStreamTest.java
  daikon-spring/daikon-spring-metrics/src/test/java/org/talend/daikon/spring/metrics/io/PartWrapperTest.java
  daikon-spring/daikon-spring-metrics/src/test/java/org/talend/daikon/spring/metrics/io/ReleasableInputStreamTest.java
  daikon-spring/daikon-spring-metrics/src/test/java/org/talend/daikon/spring/metrics/io/ReleasableOutputStreamTest.java
  daikon-spring/daikon-spring-mongo/pom.xml
  daikon-spring/daikon-spring-tenancy/pom.xml
  daikon-spring/daikon-spring-utils/pom.xml
  daikon-spring/daikon-spring-zipkin/pom.xml
  daikon-spring/pom.xml
Labels: Merged build passed, Need review

#466 fix(TDKN-222) : fix audit config appender name parsing
  daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AuditConfigurationMapImpl.java
  daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AuditConfigurationMapImplTest.java
Labels: Merged build passed

#467 fix(TDKN-222) : fix audit config appender name parsing (#466)
  daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AuditConfigurationMapImpl.java
  daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AuditConfigurationMapImplTest.java
Labels: Merged build passed

#468 chore(): Minor code style improvements in TQL -> Bean
  daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/BeanPredicateVisitor.java
  daikon-tql/daikon-tql-bean/src/test/java/org/talend/tql/bean/BeanPredicateVisitorTest.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/OrExpression.java
Labels: Merged build passed

#469 wi(TDKN-224): adding getAbsolutePath method and removing location pre…
  daikon-content-service/content-service-common/src/main/java/org/talend/daikon/content/ContextualPatternResolver.java
  daikon-content-service/content-service-common/src/main/java/org/talend/daikon/content/DeletableResource.java
  daikon-content-service/content-service-common/src/main/java/org/talend/daikon/content/ResourceResolver.java
  daikon-content-service/content-service-journal-mongo/src/main/java/org/talend/daikon/content/journal/MongoResourceJournalResolver.java
  daikon-content-service/content-service-journal-mongo/src/test/java/org/talend/daikon/content/journal/MongoResourceJournalResolverTest.java
  daikon-content-service/content-service-journal-mongo/src/test/java/org/talend/daikon/content/journal/ResourceResolverTestConfiguration.java
  daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/JournalizedResourceResolver.java
  daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/ResourceJournal.java
  daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/ResourceResolverJournal.java
  daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalContentServiceConfiguration.java
  daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalDeletableResource.java
  daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalResourceResolver.java
  daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ResourceResolver.java
Labels: Merged build passed, Need review

#471 chore(TDKN-225): Move to Greenwich.SR1 for spring-cloud
  daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/AuditConfigurationMapImpl.java
  daikon-audit/audit-common/src/test/java/org/talend/logging/audit/impl/AuditConfigurationMapImplTest.java
  daikon/src/main/java/org/talend/daikon/sandbox/properties/SunOracleStandardPropertiesStrategy.java
  pom.xml
Labels: Merged build passed

#470 wi(TDKN-224): adding getAbsolutePath method and removing location prefixe
  daikon-spring/daikon-content-service/content-service-common/src/main/java/org/talend/daikon/content/ContextualPatternResolver.java
  daikon-spring/daikon-content-service/content-service-common/src/main/java/org/talend/daikon/content/DeletableResource.java
  daikon-spring/daikon-content-service/content-service-common/src/main/java/org/talend/daikon/content/ResourceResolver.java
  daikon-spring/daikon-content-service/content-service-journal-mongo/src/main/java/org/talend/daikon/content/journal/MongoResourceJournalResolver.java
  daikon-spring/daikon-content-service/content-service-journal-mongo/src/test/java/org/talend/daikon/content/journal/MongoResourceJournalResolverTest.java
  daikon-spring/daikon-content-service/content-service-journal-mongo/src/test/java/org/talend/daikon/content/journal/ResourceResolverTestConfiguration.java
  daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/JournalizedResourceResolver.java
  daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/ResourceJournal.java
  daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/ResourceResolverJournal.java
  daikon-spring/daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalContentServiceConfiguration.java
  daikon-spring/daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalDeletableResource.java
  daikon-spring/daikon-content-service/local-content-service/src/main/java/org/talend/daikon/content/local/LocalResourceResolver.java
  daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ResourceResolver.java
Labels: Merged build passed

#472 wi(TDKN-224): fix circular injection
  daikon-content-service/content-service-journal-mongo/src/main/java/org/talend/daikon/content/journal/MongoResourceJournalResolver.java
  daikon-content-service/content-service-journal-mongo/src/test/java/org/talend/daikon/content/journal/MongoResourceJournalResolverTest.java
  daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/ResourceJournal.java
  daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/ResourceResolverJournal.java
  daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/configuration/JournalizedConfiguration.java
Labels: Merged build passed

#473 wi(TDKN-224): fix circular injection
  daikon-spring/daikon-content-service/content-service-journal-mongo/src/main/java/org/talend/daikon/content/journal/MongoResourceJournalResolver.java
  daikon-spring/daikon-content-service/content-service-journal-mongo/src/test/java/org/talend/daikon/content/journal/MongoResourceJournalResolverTest.java
  daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/ResourceJournal.java
  daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/ResourceResolverJournal.java
  daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/configuration/JournalizedConfiguration.java
Labels: Merged build passed

#478 feat: use markers to dynamically populate some custom info
  daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/LayoutUtils.java
  daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/LogbackJSONLayout.java
  daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/AbstractLayoutTest.java
  daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/LayoutUtilsTest.java
  daikon-logging/logging-event-layout/src/test/java/org/talend/daikon/logging/layout/LogBackJSONLayoutTest.java
Labels: Merged build passed

#475 feat(TDKN-229): Add more tql client operators
  daikon-tql/daikon-tql-client/README.md
  daikon-tql/daikon-tql-client/src/converter/operators/__tests__/greater-than-or-equal.spec.js
  daikon-tql/daikon-tql-client/src/converter/operators/__tests__/greater-than.spec.js
  daikon-tql/daikon-tql-client/src/converter/operators/__tests__/in.spec.js
  daikon-tql/daikon-tql-client/src/converter/operators/__tests__/less-than-or-equal.spec.js
  daikon-tql/daikon-tql-client/src/converter/operators/__tests__/unequal.spec.js
  daikon-tql/daikon-tql-client/src/converter/operators/greater-than-or-equal.js
  daikon-tql/daikon-tql-client/src/converter/operators/in.js
  daikon-tql/daikon-tql-client/src/converter/operators/index.js
  daikon-tql/daikon-tql-client/src/converter/operators/less-than-or-equal.js
  daikon-tql/daikon-tql-client/src/converter/operators/operator.js
  daikon-tql/daikon-tql-client/src/converter/operators/unequal.js
Labels: Frontend, Merged build passed, Need review

#477 fix(TDKN-227): [Java 11 support] Need an update of commons-lang3 version
  daikon-documentation/pom.xml
  daikon-exception/pom.xml
  daikon-logging/logging-event-layout/pom.xml
  daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/field/LayoutFields.java
  daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/event/layout/LogbackJSONLayout.java
  daikon-logging/logging-event-layout/src/main/java/org/talend/daikon/logging/user/RequestUserActivityFilter.java
  daikon-logging/logging-spring-security/pom.xml
  daikon-multitenant/multitenant-spring-async/pom.xml
  daikon-multitenant/multitenant-spring-web/pom.xml
  daikon-scala/dynamic-log/dynamic-log-core/pom.xml
  daikon-spring/daikon-content-service/content-service-journal-mongo/src/main/java/org/talend/daikon/content/journal/MongoResourceJournalResolver.java
  daikon-spring/daikon-content-service/content-service-journal/pom.xml
  daikon-spring/daikon-content-service/content-service-journal/src/main/java/org/talend/daikon/content/journal/configuration/IncorrectJournalConfigurationAnalyzer.java
  daikon-spring/daikon-content-service/s3-content-service/pom.xml
  daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/IncorrectS3ConfigurationAnalyzer.java
  daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/LocationUtils.java
  daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ContentServiceConfiguration.java
  daikon-spring/daikon-content-service/s3-content-service/src/main/java/org/talend/daikon/content/s3/S3ResourceResolver.java
  daikon-tql/daikon-tql-bean/pom.xml
  daikon-tql/daikon-tql-bean/src/main/java/org/talend/tql/bean/BeanPredicateVisitor.java
  daikon-tql/daikon-tql-core/pom.xml
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/AndExpression.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/ComparisonExpression.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/ComparisonOperator.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldBetweenExpression.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldCompliesPattern.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldContainsExpression.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldInExpression.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldIsEmptyExpression.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldIsInvalidExpression.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldIsValidExpression.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldMatchesRegex.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldReference.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/FieldWordCompliesPattern.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/LiteralValue.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/NotExpression.java
  daikon-tql/daikon-tql-core/src/main/java/org/talend/tql/model/OrExpression.java
  daikon-tql/daikon-tql-mongo/src/test/java/org/talend/tqlmongo/criteria/TestMongoCriteria_Abstract.java
  pom.xml
Labels: Merged build passed

#479 chores(TDKN-228) Update Guava version
  pom.xml
Labels: Merged build passed

#476 fix(TDKN-206): Fix hard-coded passphrase for encryption utility class
  Jenkinsfile
  daikon/src/main/java/org/talend/daikon/security/CryptoHelper.java
  daikon/src/main/java/org/talend/daikon/token/TokenGenerator.java
Labels: Merged build passed
